### ISSUE TITLE
connectionFailed

### ISSUE THREAD

**Issue by cksoft0807** [cabbi/modbus_client_tcp#2]
Hi,
I have tested the Huawei Sun example, unfortunately I always get an error message on client.send. Any ideas?
IP, Port, unitID an rights are correct
 
flutter: FINE: 2023-12-24 10:10:28.234722 - Connecting TCP socket...
flutter: FINE: 2023-12-24 10:10:28.293728 - Disconnecting TCP socket...
flutter: FINE: 2023-12-24 10:10:29.297294 - TCP socket connected
flutter: ModbusResponseCode.connectionFailed

**Comment by cabbi** [comment]
Hi,

Are you trying to connect to a Huawei Sun inverter?. Then please note that
you need to enable the Modbus server on the inverter.
Check out one of the procedures like this:
https://forum.huawei.com/enterprise/en/modbus-tcp-guide/thread/667250677153415168-667213868771979264

You can also put a "like" on pub dev if you enjoy using modbuls_client
package :)

Regards,
Fabio

**Comment by cksoft0807** [comment]
I overlooked the fact that my iobroker installation+wallbox is already fully utilizing the dongle. The package works perfectly.
