### ISSUE TITLE
not being able to catch a mistake

### ISSUE THREAD

**Issue by hasanuc20** [cabbi/modbus_client_tcp#4]
I wrote code like this. But I cannot catch the error when the Ethernet connection is lost, what should I do?
void startCommunication() async {
    Timer.periodic(const Duration(seconds: 1), (timer) async {
      try {
        bool isConnected = await _modbusService.isConnect();

        if (isConnected) {
          communicationState = true;
          _modbusWriteCoil.modbusCoilWrite();
        } else {
          communicationState = false;
          timer.cancel();
          reconnect();
        }
        notifyListeners();
        print(isConnected);
      } catch (e) {
        timer.cancel();
        print('hata');
      }
    });
  }
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 192.168.0.1, port = 33568

**Comment by cabbi** [comment]
Not easy to help you with partial code.

What does `modbusCoilWrite`?
You might try catch socket exceptions and reset the `isConnected` flag

**Comment by hasanuc20** [comment]
class ModbusWriteCoilAdres {
  final ModbusService _modbusService;
  final StaticToggleNotifier _staticToggle;


  ModbusWriteCoilAdres(this._modbusService, this._staticToggle);
  Future<void> modbusCoilWrite() async {
    await _modbusService.writeCoil(0, _staticToggle.m0_Bit);
    await _modbusService.writeCoil(1, _staticToggle.m1_Bit);
  }
}
client.isConnected=false;
There isn't a setter named 'isConnected' in class 'ModbusClientTcp'.
Try correcting the name to reference an existing setter, or declare the setter.
I am getting error like this. My purpose is to tell me when the internet connection is lost. and I want it to reconnect every 5 seconds.

**Comment by cabbi** [comment]
my suggestion is to set `connectionMode = ModbusConnectionMode.autoConnectAndKeepConnected` in the `ModbusClientTcp` (which is the default BTW) and then put a try catch block when sending and call `disconnect` in case of socket error.

Not sure if this thread is a real package issue... are you asking to make some changes in the modbus client handling?

**Comment by hasanuc20** [comment]
[image: hata.png]
I might be making a mistake in asynchronous operations. I did as you said,
but it doesn't catch the error.

cabbi ***@***.***>, 2 Oca 2024 Sal, 14:59 tarihinde şunu
yazdı:

**Comment by hasanuc20** [comment]
When I disconnect the ethernet socket, an error occurs in this part and my
application freezes.
 void startConnectionScan() {
    Timer.periodic(const Duration(seconds: 1), (timer) async {
      if (modbusclient.isConnected) {
        await writeCoil(0, true);
        print('bağlı');
      } else {
        print('bağlı değil');
        modbusclient.disconnect().then((_) {
          timer.cancel();
          connectWithRetry();
        });
      }
    });
  }

Future<void> writeCoil(int adres, bool value) async {
    try {
      var coil = ModbusCoil(name: 'name', address: adres);
      await modbusclient.send(coil.getWriteRequest(
        value,
        rawValue: true,
        unitId: 1,
        responseTimeout: const Duration(seconds: 2),
      ));
    } catch (e) {
      print("error: $e");
    }
  }

Hasan Uç ***@***.***>, 2 Oca 2024 Sal, 17:46 tarihinde şunu yazdı:

**Comment by cabbi** [comment]
Can you please explain in few words what you are trying to achieve (i.e. overall logic)?
Are you getting into the `print("error: $e");` part? What is it printing?

By using `ModbusConnectionMode.autoConnectAndKeepConnected` mode, your code might not handle the connection. You only have to call  `modbusclient.disconnect()` when catching the socket error and call `modbusclient.send(...)` again.

**Comment by hasanuc20** [comment]
Let me explain from the beginning. There is no problem when the ethernet socket is connected. But first of all, the ethernet socket is not plugged in. I run the application. Since I do not have ethernet plugged in, the following error appears and my application freezes.
  SocketException (SocketException: Connection timed out, host: 192.168.0.1, port: 502). I wanted to catch this error with the try-catch structure, but I cannot catch it. My application freezes.
print(error $e); Nothing comes, the app
lication freezes immediately.
![sss](https://github.com/cabbi/modbus_client_tcp/assets/135219553/11544feb-14e5-4719-9677-d0f732ce19a4)
![dd](https://github.com/cabbi/modbus_client_tcp/assets/135219553/95f567c9-c2f2-476d-9462-ec48ebbd44e3)

**Comment by hasanuc20** [comment]
The second part is the ethernet socket connection. My application is working. I check the connection every 1 second. If I disconnect the ethernet cable and disconnect, my application freezes. I shared the screenshots. What should I do?
![fff](https://github.com/cabbi/modbus_client_tcp/assets/135219553/0657ad07-e226-4e8e-9877-54eabb5718aa)

**Comment by cabbi** [comment]
From the picture you sent I see you catch the _SocketException: Connection timed out_ exception in the `try...catch` at line 15 (i.e. your `connect` method), so why are you saying you cannot catch it?

**Comment by cabbi** [comment]
Did you find a solution to this issue? Can you close it in case?
