### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by cksoft0807** [cabbi/modbus_client_tcp#6]
first of all, thanks for the great component. from time to time i have a zero check error like the following... In my opinion, this error did not exist in earlier versions.

/flutter (30085): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (30085): #0      ModbusClientTcp._onSocketData (package:modbus_client_tcp/src/modbus_client_tcp.dart:151:21)
E/flutter (30085): #1      ModbusClientTcp.connect.<anonymous closure> (package:modbus_client_tcp/src/modbus_client_tcp.dart:130:9)
E/flutter (30085): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (30085): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (30085): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30085): #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (30085): #6      _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (30085): #7      _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (30085): #8      _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
E/flutter (30085): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (30085): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (30085): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30085): #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (30085): #13     _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (30085): #14     _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (30085): #15     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
E/flutter (30085): #16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
E/flutter (30085): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (30085): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (30085):

**Comment by cabbi** [comment]
I think it's due to buffered data. I've released version 1.0.7 that should resolve this issue..
