### ISSUE TITLE
Would you support 0x06 function code for writing float32 values? 

### ISSUE THREAD

**Issue by yqz1119** [cabbi/modbus_client_tcp#8]
I'm using the example 'write_request.dart', but I found 'enum BatteryStatus implements ModbusIntEnum{...}' only supports int16.
How to write float32 values to single or multiple Registers(function code 0x06 and 0x10)?

**Comment by cabbi** [comment]
What I understood is you want to have a float32 numeric registry type, correct?
What has the 'enum BatteryStatus' example to do with your foat32 request?

**Comment by yqz1119** [comment]
:) I found I can use 'ModbusInt32Register' to express Float32 values.
Really appreciate your work. Thanks!
